spring.application.name=user-service
spring.cloud.config.import-check.enabled=false
server.port = 8081
spring.datasource.url=jdbc:mysql://localhost:3306/userdb
spring.datasource.username=root
spring.datasource.password=0000
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
jwt.secret = 216537fcbef2e15015f058dbb8195ce33bced1258d0e5e0d4cfb221d1e49fbef
# ===============================
# = JPA / HIBERNATE CONFIG      =
# ===============================

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.properties.hibernate.format_sql=true

# ===============================

# = EUREKA CLIENT CONFIGURATION =

# ===============================

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

eureka.instance.hostname=localhost

eureka.client.register-with-eureka=true

eureka.client.fetch-registry=true