spring.application.name=api-gateway
server.port = 8765

jwt.secret = 216537fcbef2e15015f058dbb8195ce33bced1258d0e5e0d4cfb221d1e49fbef


eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# Enable routing by service name
spring.cloud.gateway.discovery.locator.enabled=true
spring.cloud.gateway.discovery.locator.lower-case-service-id=true

